# 每12小时执行一次

name: Start

on:
   push:
   gollum:
   schedule:
       - cron: '30 */12 * * *'

jobs:
  TiebaSignIn:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: 8
        distribution: "adopt"
        cache: maven
    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      env:
        BDUSS: ${{ secrets.BDUSS }}
        SCKEY: ${{ secrets.SCKEY }}
      run: |
        mvn compile exec:java -Dexec.mainClass="top.srcrs.Run" -Dexec.args="${BDUSS} ${SCKEY}"

    - name: Keepalive Workflow
      uses: gautamkrishnar/keepalive-workflow@v1
